---

- name: Get CA certs stats
  stat:
    path: "{{ ssc.output_dir }}/{{ item }}"
  register: ca_certs_stats
  with_items:
    - ca-key.pem
    - ca.csr
    - ca.pem

- name: Check if CA certs exists
  set_fact:
    ca_certs_exists: "{{
      ca_certs_stats.results[0].stat.exists and
      ca_certs_stats.results[1].stat.exists and
      ca_certs_stats.results[2].stat.exists }}"

- name: Get Server certs stats
  stat:
    path: "{{ ssc.output_dir }}/{{ item }}"
  register: server_certs_stats
  with_items:
    - server-key.pem
    - server.csr
    - server.pem
    - server.pfx

- name: Check if Server certs exists
  set_fact:
    server_certs_exists: "{{
      server_certs_stats.results[0].stat.exists and
      server_certs_stats.results[1].stat.exists and
      server_certs_stats.results[2].stat.exists and
      server_certs_stats.results[3].stat.exists }}"

- name: Get Client certs stats
  stat:
    path: "{{ ssc.output_dir }}/{{ item }}"
  register: client_certs_stats
  with_items:
    - client-key.pem
    - client.csr
    - client.pem
    - client.pfx

- name: Check if Client certs exists
  set_fact:
    client_certs_exists: "{{
      client_certs_stats.results[0].stat.exists and
      client_certs_stats.results[1].stat.exists and
      client_certs_stats.results[2].stat.exists and
      client_certs_stats.results[3].stat.exists }}"