---

- name: Ensure cfssl executable is installed
  get_url:
    url: "{{ selfSignedCerts. cfsslUrl }}"
    dest: "/usr/local/bin/cfssl"
    mode: 0755

- name: Ensure cfssl executable is installed
  get_url:
    url: "{{ selfSignedCerts. cfssljsonUrl }}"
    dest: "/usr/local/bin/cfssljson"
    mode: 0755