---

- name: Ensure cfssl tools are installed
  include: install_cfssl.yml

- name: Ensure csr files are generated
  include: generate_csr.yml

- name: Ensure ca certs are generated
  include: generate_ca.yml

- name: Ensure certs are generated
  include: generate_certs.yml